ci: Remove pnpm version from publish workflow (#77)
This failed because I also have the pnpm version saved in package.json:


https://github.com/developmentseed/deck.gl-raster/actions/runs/20351997654/job/58478667252
```
  Error: Multiple versions of pnpm specified:
    - version 10 in the GitHub Action config with the key "version"
    - version pnpm@10.25.0 in the package.json with the key "packageManager"
```